export const startups = [
    { id: 1, name: "OpenLearn", domain: "EdTech", studentNames: ["Vatsal Khanna"], students: ["ECE124632"], contact: "medicare@college.edu", description: "Early disease detection using AI analysis of retinal scans.", startDate: "February 2024", status: "Active", fundingStage: "Grant", image: "https://www.openlearn.org.in/favicon.png" },
    { id: 2, name: "The Startup Arc", domain: "FinTech", studentNames: ["Javin Chutani"], students: ["24117014"], contact: "javinc.ds.24@nitj.ac.in", description: "Getting early stage startups the dedicated platform they need.", startDate: "April 2024", status: "In Progress", fundingStage: "Bootstrapped", image: "https://media.licdn.com/dms/image/v2/D4D03AQFgQR2lMXJrnQ/profile-displayphoto-shrink_800_800/profile-displayphoto-shrink_800_800/0/1727542556872?e=1767225600&v=beta&t=xzs7e_8h2dgjTDuNB2bqvP3seCPGoPrAFUSIncOYvqY" },
    { id: 3, name: "Adisun", domain: "Chemical Distribution", studentNames: ["Abhishek Bhatti"], students: ["24103004"], contact: "abhishekb.cs.24@nit.ac.in", description: "Autonomous drones for soil analysis and crop monitoring.", startDate: "January 2024", status: "Active", fundingStage: "Seed", image: "https://raw.githubusercontent.com/A-nshuman/DVPD_Dashboard/refs/heads/main/src/assets/bhatti.png" },
    { id: 4, name: "NATIVE", domain: "E-Commerce", studentNames: ["Jashan Aneja"], students: ["24117013"], contact: "jashana.ds.24@nitj.ac.in", description: "Automated vulnerability scanner for small businesses.", startDate: "May 2024", status: "Active", fundingStage: "Pre-seed", image: "https://raw.githubusercontent.com/A-nshuman/DVPD_Dashboard/refs/heads/main/src/assets/jashan.jpg" },
    { id: 5, name: "EcoPack", domain: "Sustainability", studentNames: ["Pooja Iyer"], students: ["2021CH015"], contact: "ecopack@college.edu", description: "Biodegradable packaging material made from agricultural waste.", startDate: "December 2023", status: "Active", fundingStage: "Grant", image: "https://images.unsplash.com/photo-1542601906990-b4d3fb7d5763?w=400&h=250&fit=crop" },
    { id: 6, name: "FitTrack", domain: "Wellness", studentNames: ["Varun Kapoor"], students: ["2022CS019"], contact: "fittrack@college.edu", description: "Wearable device for tracking student mental health and stress.", startDate: "June 2024", status: "In Progress", fundingStage: "Bootstrapped", image: "https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=400&h=250&fit=crop" },
    { id: 7, name: "RoboAssist", domain: "Robotics", studentNames: ["Karan Singh"], students: ["2020EC091"], contact: "roboassist@college.edu", description: "Robotic arms for assisting in hazardous chemical handling.", startDate: "November 2023", status: "Completed", fundingStage: "Series A", image: "https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=400&h=250&fit=crop" },
    { id: 8, name: "UrbanCommute", domain: "Transportation", studentNames: ["Riya Deshmukh"], students: ["2021CE018"], contact: "urbancommute@college.edu", description: "Ride-sharing app specifically for inter-campus transport.", startDate: "July 2024", status: "Active", fundingStage: "Pre-seed", image: "https://images.unsplash.com/photo-1449965408869-eaa3f722e40d?w=400&h=250&fit=crop" },
    { id: 9, name: "SmartHome IO", domain: "IoT", studentNames: ["Tarun Bhatia"], students: ["2021EC050"], contact: "smarthome@college.edu", description: "Modular IoT system for energy efficient hostel rooms.", startDate: "March 2024", status: "Active", fundingStage: "Bootstrapped", image: "https://images.unsplash.com/photo-1558002038-1091a1661116?w=400&h=250&fit=crop" },
    { id: 10, name: "LangBridge", domain: "EdTech", studentNames: ["Aryan Saxena"], students: ["2022BA002"], contact: "langbridge@college.edu", description: "Real-time translation tool for regional language speakers.", startDate: "August 2024", status: "Idea Phase", fundingStage: "None", image: "https://images.unsplash.com/photo-1543269865-cbf427effbad?w=400&h=250&fit=crop" },
];

export const research = [
    { id: 1, name: "Graph Theroy", domain: "Computer Science", studentNames: ["Anshuman Bhardwaj"], students: ["24103017"], contact: "anshumanb.cs.24@nitj.ac.in", description: "Optimizing quantum algorithms for cryptography.", startDate: "August 2023", status: "Ongoing", type: "under_prof", professor: "Dr. Sharma", professorDept: "CSE", publications: 2, image: "https://raw.githubusercontent.com/A-nshuman/DVPD_Dashboard/refs/heads/main/src/assets/anshuman.jpg" },
    { id: 2, name: "Glaucoma Detection", domain: "Biomedical", studentNames: ["Ishaan Verma"], students: ["2021BM005"], contact: "biomed@college.edu", description: "CNN based early detection of Glaucoma from fundus images.", startDate: "January 2024", status: "Ongoing", type: "under_prof", professor: "Dr. Iyer", professorDept: "BioTech", publications: 1, image: "https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=400&h=250&fit=crop" },
    { id: 3, name: "Sustainable Concrete", domain: "Civil", studentNames: ["Arjun Malhotra"], students: ["2020CE045"], contact: "green@college.edu", description: "Analysis of plastic waste in concrete mixtures.", startDate: "September 2023", status: "Completed", type: "grant_funded", professor: "Dr. Gill", PvD: "Civil", publications: 3, image: "https://images.unsplash.com/photo-1590486803833-1c5dc8ce2ac6?w=400&h=250&fit=crop" },
    { id: 4, name: "Swarm Robotics", domain: "Robotics", studentNames: ["Vikram Rao"], students: ["2021RA002"], contact: "swarm@college.edu", description: "Swarm intelligence in disaster management robots.", startDate: "March 2023", status: "Ongoing", type: "under_prof", professor: "Dr. Kulkarni", professorDept: "Mech", publications: 0, image: "https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=400&h=250&fit=crop" },
    { id: 5, name: "Supply Chain Blockchain", domain: "IT", studentNames: ["Neha Agarwal"], students: ["2020IT088"], contact: "crypto@college.edu", description: "Implementation of Hyperledger Fabric in Pharma supply chain.", startDate: "November 2023", status: "Ongoing", type: "independent", professor: "Prof. Roy", professorDept: "IT", publications: 1, image: "https://images.unsplash.com/photo-1639322537228-f710d846310a?w=400&h=250&fit=crop" },
    { id: 6, name: "Perovskite Solar", domain: "Material Science", studentNames: ["Karan Patel"], students: ["2022MS004"], contact: "solar@college.edu", description: "Efficiency enhancement in Perovskite Solar Cells.", startDate: "February 2024", status: "Ongoing", type: "under_prof", professor: "Dr. Thomas", professorDept: "Physics", publications: 0, image: "https://images.unsplash.com/photo-1509391366360-2e959784a276?w=400&h=250&fit=crop" },
    { id: 7, name: "Regional NLP", domain: "Computer Science", studentNames: ["Manoj Krishnan"], students: ["2020CS102"], contact: "nlp@college.edu", description: "Translation model for low-resource Indian languages.", startDate: "August 2022", status: "Published", type: "grant_funded", professor: "Dr. Venkataraman", professorDept: "CSE", publications: 4, image: "https://images.unsplash.com/photo-1555949963-ff9fe0c870eb?w=400&h=250&fit=crop" },
    { id: 8, name: "Microplastics", domain: "Env Science", studentNames: ["Riya Nair"], students: ["2021ES033"], contact: "water@college.edu", description: "Detection of microplastics in local water bodies.", startDate: "June 2023", status: "Completed", type: "under_prof", professor: "Dr. Siddiqui", professorDept: "Chemistry", publications: 2, image: "https://images.unsplash.com/photo-1617155093730-a8bf47be792d?w=400&h=250&fit=crop" },
    { id: 9, name: "Smart Grid", domain: "Electrical", studentNames: ["Devendra Kumar"], students: ["2020EE014"], contact: "grid@college.edu", description: "Load balancing in smart grids using AI.", startDate: "October 2023", status: "Ongoing", type: "under_prof", professor: "Prof. Das", professorDept: "Electrical", publications: 1, image: "https://images.unsplash.com/photo-1473341304170-971dccb5ac1e?w=400&h=250&fit=crop" },
    { id: 10, name: "CRISPR Drought", domain: "Biotech", studentNames: ["Tara Banerjee"], students: ["2021BT007"], contact: "genetics@college.edu", description: "CRISPR editing for drought resistance in rice.", startDate: "January 2023", status: "Ongoing", type: "under_prof", professor: "Dr. Gupta", professorDept: "BioTech", publications: 2, image: "https://images.unsplash.com/photo-1530836369250-ef72a3f5cda8?w=400&h=250&fit=crop" },
    { id: 11, name: "Drone Aerodynamics", domain: "Aerospace", studentNames: ["Sameer Khan"], students: ["2022AE019"], contact: "aero@college.edu", description: "CFD analysis of quadcopter propeller blades.", startDate: "April 2024", status: "Just Started", type: "independent", professor: "Dr. D'Souza", professorDept: "Aero", publications: 0, image: "https://images.unsplash.com/photo-1527977966376-1c8408f9f108?w=400&h=250&fit=crop" },
];
